#Minecraft server properties
#All the Mods 9 - To the Sky (ATM9 Sky) 1.1.8
server-port=25565
online-mode=true
level-name=world
level-type=default
difficulty=normal
gamemode=survival
allow-flight=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
generate-structures=true
max-players=20
view-distance=10
simulation-distance=8
spawn-protection=0
enable-command-block=true
white-list=false
pvp=true
hardcore=false
max-build-height=320
enforce-secure-profile=false
enable-rcon=true
rcon.port=25575
rcon.password=Hackers11!@
motd=All the Mods 9 - To the Sky Server
snooper-enabled=false
