@echo off
title ATM9 Sky 1.1.8 Server

if not exist run.bat (
    echo ERROR: Forge is not installed yet.
    echo Please run setup_server.ps1 first:
    echo   powershell -ExecutionPolicy Bypass -File setup_server.ps1
    pause
    exit /b 1
)

echo Starting All the Mods 9 - To the Sky 1.1.8 Server...
echo RCON is enabled on port 25575
echo.

:: JVM memory settings - edit user_jvm_args.txt to change heap sizes
:: Forge 1.20.1 uses run.bat generated by the installer
call run.bat nogui

pause
