#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 02 12:41:42 MST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
